# Construcción del artefacto con NODE.JS

FROM node:22-bookworm AS build-step
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# Manda el artefacto a un servidor web (nginx)

FROM nginx:1.27-bookworm
LABEL maintainer="aleshit2021@gmail.com"
ENV APP_ENV=production
COPY --from=build-step /app/dist /usr/share/nginx/html
VOLUME /var/log/nginx
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]